name: haskell-lox
version: 0.1.0.0
github: "githubuser/haskell-lox"
license: BSD3
author: "Wolfgang Schuster"
maintainer: "example@example.com"
copyright: "2022 Wolfgang Schuster"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/wolfadex/many-lox>

dependencies:
  - base >= 4.7 && < 5
  - containers

library:
  source-dirs: src

executables:
  haskell-lox-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-lox

tests:
  haskell-lox-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-lox
